name: Clean All Artifacts

on:
  workflow_dispatch: # يتيح لك تشغيل الـ Workflow يدوياً بضغطة زر

jobs:
  clean-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write # تصريح ضروري جداً للسماح للأكشن بحذف الـ Artifacts
    steps:
      - name: Delete all artifacts
        uses: actions/delete-artifact@v3
        with:
          name: "*" # علامة النجمة تعني تحديد وحذف كل شيء
