name: Quran Shorts Generator

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write   # ✅ مهم جدا

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true   # ✅ مهم

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          ffmpeg \
          libcairo2-dev \
          libpango1.0-dev \
          libglib2.0-dev \
          pkg-config \
          shutil \
          python3-dev \
          fonts-dejavu-core

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install manim mutagen pydub requests numpy

    - name: Register local font
      run: |
        mkdir -p ~/.fonts
        cp Amiri-Regular.ttf ~/.fonts/
        fc-cache -fv

    - name: Run script
      run: python Quran.py

    - name: Upload video
      uses: actions/upload-artifact@v4
      with:
        name: quran-short
        path: |
          Quran_Normal.mp4
          Quran_Shorts.mp4

    - name: Commit used ayahs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add used_ayahs.json
        git commit -m "update used ayahs" || echo "no changes"
        git push
